<h1>NumPy - Numberical Python</h1>
<h3>Advantages of NumPy Arrays</h3>
<p>1. Allow Several Mathematical Operations</p>
<p>2. Faster Operations</p>

In [1]:
import numpy as np


<p>creating np array</p>
<p>.shape shows number of rows and columns here [4,] column</p>

In [5]:
# 1 dimensional Array
a = np.array([1,2,3,4])
print(a)
# Shape to represent row and column
a.shape
# here is show like 4 column

[1 2 3 4]


(4,)

<p>creating np 2D array</p>
<p>np.array([(1,3,4),(4,5,5),dtype=fload])</p>
<p>dtype=fload - convert into fload type</p>




In [6]:
# 2 dimensional Array
nums = np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)
print(nums)
nums.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)

<h1>List Disadvantages</h1>
<p>List take more time to perform operation on data in list</p>

<h1>Placeholders</h1>
<p>initial placeholders in numpy array</p>


In [8]:
# create a numpy array of Zeros
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# create a numpy array of Ones
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# create a numpy array of particular value
z = np.full((5,5),5)
z

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
# create a numpy array of Identity matrix
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# create a numpy array of random values
x = np.random.random((5,5))
x

array([[0.37582188, 0.63096197, 0.33190599, 0.11264802, 0.23721705],
       [0.34430999, 0.59729415, 0.08795671, 0.52420411, 0.17962165],
       [0.50904803, 0.57290562, 0.58667784, 0.66595877, 0.20948585],
       [0.06104473, 0.55205555, 0.58782088, 0.93101102, 0.47555091],
       [0.65844134, 0.10689429, 0.23574114, 0.74861535, 0.62743028]])

In [24]:
# create a numpy array of random between specific range
x = np.random.randint(10,100,(5,5))
x

array([[61, 17, 83, 62, 11],
       [30, 21, 22, 73, 26],
       [65, 85, 55, 78, 59],
       [94, 88, 47, 91, 29],
       [20, 83, 65, 37, 27]], dtype=int32)

In [2]:
import numpy as np
# create a numpy array of Event spaced value ===> specifying the number of values required
x = np.linspace(10,30,5)
x

array([10., 15., 20., 25., 30.])

In [38]:
# create a numpy array of evenly spaced but specifying the step
x = np.arange(10,30,10)
x

array([10, 20])

<h1>Convert the list to numpy array</h1>

In [40]:
# convert the list to numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
np_array
type(np_array)

numpy.ndarray

<h1>Analysis of numpy array</h1>

In [45]:
# Array of dimensional 

x = np.array([(1,2),(3,4)])
x.shape

(1, 2)

In [46]:
# for no. of dimensional 

x = np.array([(1,2),(3,4)])
x.ndim

2

In [49]:
# no. of elements in an array

x = np.array([(1,2,3),(3,4,3)])
x.size

6

In [50]:
# Type Array 

x = np.array([(1,2),(3,4)])
x.dtype

dtype('int64')

<h1> Mathemical Operation on Numpy array</h1>

In [51]:
# Merge Array 

list1 = [1,3,5]
list2 = [2,4,6]
print(list1 + list2)

[1, 3, 5, 2, 4, 6]


In [60]:
# do with Numpy 
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 2 2]
 [7 5 6]
 [5 9 4]]
[[16 17 16]
 [10 11 17]
 [16 17 18]]


<h1>Commonly </h1>

In [61]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[17 19 18]
 [17 16 23]
 [21 26 22]]
[[-15 -15 -14]
 [ -3  -6 -11]
 [-11  -8 -14]]
[[ 16  34  32]
 [ 70  55 102]
 [ 80 153  72]]
[[0.0625     0.11764706 0.125     ]
 [0.7        0.45454545 0.35294118]
 [0.3125     0.52941176 0.22222222]]


<h1>Using Numpy for Operation</h1>

In [65]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 19 18]
 [17 16 23]
 [21 26 22]]
[[-15 -15 -14]
 [ -3  -6 -11]
 [-11  -8 -14]]
[[ 16  34  32]
 [ 70  55 102]
 [ 80 153  72]]
[[0.0625     0.11764706 0.125     ]
 [0.7        0.45454545 0.35294118]
 [0.3125     0.52941176 0.22222222]]


<h1>Array Manipulation</h1>

In [66]:
array = np.random.randint(0,10,(2,3))
array

array([[3, 4, 0],
       [6, 9, 5]], dtype=int32)

<h1>Transpose</h1>

In [69]:
trans = np.transpose(array)
trans.shape
print(trans)

[[3 6]
 [4 9]
 [0 5]]


In [71]:
# Another way for transpose 

x = np.array([(1,2),(3,4)])
trans2 = x.T
print(trans2)

[[1 3]
 [2 4]]


<h1>Reshape</h1>

In [73]:
a = np.random.randint(0,10,(2,3))
a.shape
print(a)

[[1 1 7]
 [6 7 0]]


In [82]:
b = a.reshape(3,2)
b.shape
print(b)

[[1 1]
 [7 6]
 [7 0]]
