<h1>NumPy - Numberical Python</h1>
<h3>Advantages of NumPy Arrays</h3>
<p>1. Allow Several Mathematical Operations</p>
<p>2. Faster Operations</p>

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
# 1 dimensional Array
a = np.array([1,2,3,4])
print(a)
# Shape to represent row and column
a.shape
# here is show like 4 column

[1 2 3 4]


(4,)

In [10]:
# 2 dimensional Array
nums = np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)
print(nums)
nums.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)